apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: metarab
#common configuration shared between all applications
data:
  application.yml: |-
    configserver:
      name:  JHipster Registry
      status: Connected to the JHipster Registry running in Kubernetes
    eureka:
      client:
        initial-instance-info-replication-interval-seconds: 15
        instance-info-replication-interval-seconds: 15
        registry-fetch-interval-seconds: 15
        fetch-registry: true
        register-with-eureka: true
        eureka-service-url-poll-interval-seconds: 15
      instance:
        lease-renewal-interval-in-seconds: 10
        registry-default-open-for-traffic-count: 0
    jhipster:
      security:
        authentication:
          jwt:
            base64-secret: OGI1MDFmZGQzNjAyMjgxNGYxNmZmMDI2Y2RmNzM1ODYyY2U5YTEyNzcyZjc1ZDNlNTkyNGNkYjZkMDUwYTJiZjM1M2Y1MTM5NmMwZjk0NTMyNTJkNTQxMTAxZDMyOTRmY2E2ZWNiNWI2MzVmZmM3YTlmZDBkYWQ5YTA5MzMzZDM=
  # app specific configuration
  jhipster-registry.yml: |-
    eureka:
      client:
        service-url:
          defaultZone: http://admin:${spring.security.user.password}@jhipster-registry-0.jhipster-registry.metarab.svc.cluster.local:8761/eureka/,http://admin:${spring.security.user.password}@jhipster-registry-1.jhipster-registry.metarab.svc.cluster.local:8761/eureka/
