apiVersion: apps/v1
kind: Deployment
metadata:
  name: metarab-mysql
  namespace: metarab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metarab-mysql
  template:
    metadata:
      labels:
        app: metarab-mysql
    spec:
      volumes:
        - name: pvc-data-db
          persistentVolumeClaim:
            claimName: pvc-data-db
      initContainers:
        - name: remove-lostfound
          image: busybox
          command: ["rm", "-rf", "/var/lib/mysql/*"]
          securityContext:
            privileged: true
      containers:
        - name: mysql
          image: mariadb:10.5
          env:
            - name: MYSQL_USER
              value: root
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: 'yes'
            - name: MYSQL_DATABASE
              value: metarab
          args:
            - --ignore-db-dir=lost+found
            - --lower_case_table_names=1
            - --skip-ssl
            - --character_set_server=utf8mb4
            - --explicit_defaults_for_timestamp
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: pvc-data-db
              mountPath: /var/lib/mysql/data
          resources:
            requests:
              memory: '1Gi'
              cpu: '1'
            limits:
              memory: '2Gi'
              cpu: '2'
---
apiVersion: v1
kind: Service
metadata:
  name: metarab-mysql
  namespace: metarab
spec:
  selector:
    app: metarab-mysql
  ports:
    - port: 3306
