apiVersion: apps/v1
kind: Deployment
metadata:
  name: metarab-elasticsearch
  namespace: metarab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metarab-elasticsearch
  template:
    metadata:
      labels:
        app: metarab-elasticsearch
    spec:
      volumes:
        - name: pvc-data-es
          persistentVolumeClaim:
            claimName: pvc-data-es
      initContainers:
        - name: init-sysctl
          image: busybox
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
          volumeMounts:
            - name: pvc-data-es
              mountPath: /usr/share/elasticsearch/data/
          resources:
            requests:
              memory: '1Gi'
              cpu: '1'
            limits:
              memory: '2Gi'
              cpu: '2'
---
apiVersion: v1
kind: Service
metadata:
  name: metarab-elasticsearch
  namespace: metarab
spec:
  selector:
    app: metarab-elasticsearch
  ports:
    - port: 9200
      name: http
      protocol: TCP
    - port: 9300
      name: transport
      protocol: TCP
