apiVersion: v1
kind: Service
metadata:
  name: metarab
  namespace: metarab
  labels:
    app: metarab
spec:
  selector:
    app: metarab
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
