version: '2'
services:
  metarab-app:
    image: metarab/metarab:v1.3
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://metarab-mysql:3306/metarab?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://metarab-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://metarab-elasticsearch:9200
    ports:
      - 8080:8080
  metarab-mysql:
    extends:
      file: mysql.yml
      service: metarab-mysql
  metarab-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: metarab-elasticsearch
