version: '2'
services:
  metarab-mysql:
    image: mysql:5.7
    # volumes:
    #     - ~/volumes/jhipster/metarab/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=salamsql2019
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_PASSWORD=salamsql2019
      - MYSQL_DATABASE=metarab
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
